version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:8081"
    volumes:
      # - ./injectionpage:/code
      - ./web:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  php:
    image: php:7-fpm
    volumes:
      # - ./injectionpage:/code
      - ./web:/code
    networks:
      - code-network

networks:
  code-network:
    driver: bridge